# Generated by Django 4.0.3 on 2022-03-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_editor_phone_number_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(null=b'I01\n', upload_to='articles/'),
            preserve_default=b'I01\n',
        ),
    ]
